apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata: # kpt-merge: /generate-values
  name: generate-values
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: fn.kpt.dev|StarlarkRun|default|generate-values
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
source: |-
  load("krmfn.star", "krmfn")
  def set_values(resources):
    clusterName = "s"
    node_ip = "192.18.0.200"
    http_port = "3001"

    # this package can be cloned manually and used without injection; in that case base
    # the repository name on the package name
    for r in resources:        
      if krmfn.match_gvk(r, "v1", "ConfigMap") and krmfn.match_name(r, "repo-service-node-ip"):
        node_ip = r["data"]["node-ip"]
        http_port = r["data"]["node-port"]

    # if a WorkloadCluster exists, and was injected, then use that for the name
    for r in resources:
      if krmfn.match_gvk(r, "infra.nephio.org/v1alpha1", "WorkloadCluster") and "annotations" in r["metadata"] and "kpt.dev/injected-resource" in r["metadata"]["annotations"]:
        clusterName = r["spec"]["clusterName"]
      
    for r in resources:
      if krmfn.match_gvk(r, "argoproj.io/v1alpha1", "Application"):
        r["spec"]["source"]["repoURL"] = "http://" + node_ip + ":"+ http_port +"/nephio/dr.git"
        r["spec"]["source"]["path"] = "/"+clusterName
      elif krmfn.match_gvk(r, "configsync.gke.io/v1beta1", "RootSync"):
        r["metadata"]["name"] = clusterName
        r["spec"]["git"]["repo"] = "http://" + node_ip + ":"+ http_port +"/nephio/" + clusterName + ".git"
        r["spec"]["git"]["secretRef"]["name"] = clusterName + "-access-token-configsync"
  set_values(ctx.resource_list["items"])