apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata: 
  name: cucp-example
  namespace: example
spec:
  provider: cucp.openairinterface.org
  interfaces:
  - name: n2
    ipv4:
      address: 192.168.8.55/24 #CUCP_N2_IP
      gateway: 192.168.8.1 #CUCP_N2_GW
  - name: f1c
    ipv4:
      address: 192.168.10.21/24 #CUCP_F1C_IP
      gateway: 192.168.10.1 #CUCP_F1C_GW
  - name: e1
    ipv4:
      address: 192.168.11.20/24 #CUCP_E1_IP
      gateway: 192.168.11.1 #CUCP_E1_GW
  networkInstances:
  - name: vpc-ran
    interfaces:
    - n2
  - name: vpc-cudu-f1
    interfaces:
    - f1c
  - name: vpc-cu-e1
    interfaces:
    - e1
  parametersRefs:
  - apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
    name: cucp-nf-config
  - name: cucp-ran-amf-core
    apiVersion: ref.nephio.org/v1alpha1
    kind: Config