apiVersion: ref.nephio.org/v1alpha1
kind: Config
metadata:
  name: oai-cucp-config
  namespace: example
  annotations:
    specializer.nephio.org/owner: req.nephio.org/v1alpha1.Dependency.cucp
spec:
  config:
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFDeployment
    metadata:
      name: cucp-core
      namespace: oai-cucp
      annotations:
        config.kubernetes.io/index: "0"
        internal.config.kubernetes.io/index: "0"
        internal.config.kubernetes.io/path: cucpdeployment.yaml
        internal.kpt.dev/upstream-identifier: workload.nephio.org|NFDeployment|example|cucp-example
    spec:
      interfaces:
      - name: n2
        ipv4:
          address: 192.168.8.55/24 #CUCP_N2_IP
          gateway: 192.168.8.1 #CUCP_N2_GW
      - name: f1c
        ipv4:
          address: 192.168.10.21/24 #CUCP_F1C_IP
          gateway: 192.168.10.1 #CUCP_F1C_GW
      - name: e1
        ipv4:
          address: 192.168.11.20/24 #CUCP_E1_IP
          gateway: 192.168.11.1 #CUCP_E1_GW
      parametersRefs:
      - name: oai-cucp-config
        apiVersion: workload.nephio.org/v1alpha1
        kind: NFConfig
      - name: cucp-ran-amf-core
        apiVersion: ref.nephio.org/v1alpha1
        kind: Config
      provider: cucp.openairinterface.org