apiVersion: v1
data:
  cacert: Cg==
  clouds.yaml: Y2xvdWRzOgogIG9wZW5zdGFjazoKICAgIGF1dGg6CiAgICAgIGF1dGhfdXJsOiBodHRwOi8vMTkyLjE2OC4yOC4xMDo1MDAwCiAgICAgIHVzZXJuYW1lOiAiYWRtaW4iCiAgICAgIHBhc3N3b3JkOiAiYWRtaW4iCiAgICAgIHByb2plY3RfaWQ6IDZjNmU3M2VjMGJmYTQ0YTI5N2U2NmQ4NDA1MDM3ZGEzCiAgICAgIHByb2plY3RfbmFtZTogImFkbWluIgogICAgICB1c2VyX2RvbWFpbl9uYW1lOiAiRGVmYXVsdCIKICAgIHJlZ2lvbl9uYW1lOiAiUmVnaW9uT25lIgogICAgaW50ZXJmYWNlOiAicHVibGljIgogICAgaWRlbnRpdHlfYXBpX3ZlcnNpb246IDMK
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  name: example-cloud-config
  namespace: default
